adding use cases
dyc3/ssw345-group-assignments pull request #43
Opened 2023-04-19 23:48 UTC by sophiadicuffa

2023-04-20 01:01 UTC, dyc3 commented
I will review this tomorrow pinkie promise

2023-04-20 11:11 UTC, dyc3 requested changes

2023-04-20 11:11 UTC, dyc3 commented on final-project/Figures/hosting-use-case.mmd
> +Heroku -- Deploy --> Website
```suggestion
Heroku -- Hosts --> Website
```

2023-04-20 11:11 UTC, dyc3 commented on final-project/Figures/hosting-use-case.mmd
Technically, Heroku _is_ the deployment pipeline.

2023-04-20 11:11 UTC, dyc3 commented on final-project/Figures/enduser-usecase.mmd
This is not really a useful diagram because it doesn't cover the behavior that is most relevant to this project. Is this supposed to close #39? If so, using a state diagram would be more useful to convey the different entry points: https://mermaid.js.org/syntax/stateDiagram.html

2023-04-20 17:15 UTC, dyc3 requested changes

2023-04-20 17:15 UTC, dyc3 commented on final-project/Figures/api-credentials.mmd
> +        TokenVerification -->|Authenticated| VideoStream((Video Stream))
OTT does not stream video. This should be something along the lines of the HTTP request is being authorized.

2023-04-29 15:28 UTC, evanciok approved these changes

2023-04-29 15:28 UTC, dyc3 approved these changes

2023-04-29 15:28 UTC, merged