updated diagrams
dyc3/ssw345-group-assignments pull request #57
Opened 2023-05-04 23:30 UTC by sophiadicuffa

* changed balancer-internals and client-connection

2023-05-05 00:13 UTC, dyc3 requested changes
Please indicate which issues this PR closes

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

2023-05-05 13:09 UTC, dyc3 commented
Please use keywords in the PR description to link the issues, so they get closed automatically.

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

Also, please remember to assign yourself to the issues you are working on so we don't duplicate effort

2023-05-11 16:11 UTC, sophiadicuffa commented
I belive I fixed

2023-05-11 16:15 UTC, dyc3 approved these changes

2023-05-11 16:15 UTC, merged